# Generated by Django 3.2.13 on 2023-07-13 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_store_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('disc', models.TextField()),
                ('price', models.IntegerField()),
                ('pimage', models.ImageField(upload_to='prod_img/')),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.catagory')),
            ],
        ),
        migrations.CreateModel(
            name='Top_product',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.product')),
            ],
        ),
    ]
